language: ruby
cache:
- bundler
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
- bundle exec rake db:test:prepare
deploy:
  provider: heroku
  api_key:
    secure: "uWiYQCzPI6PG2CdgBS3Wjq0OvryUn1OyYMKT58Em7Aw4JLVIGGYq52+BWo93xKdSXy9NBQ5OEAxCuUXlPPbZMVhNNTzirm99ROyfR/A38HWmVw6Gv8F3Gh4XDR4M5aJNrCcY3iNestpCY4ytrDYiQOFjTfZFVMeDwubzLUS5I18aMYY5Ibp+WGTwB3k761eyQnSqlqgWROfFdqXUfV31tinRxC3W8sX6LEGroDNBVGC+IPH0sNsKm8BXU8mWxKaDlKTByzO/UR2KN4kNAGtJXkP/loDETRcvBn7v3qNqF2hn+PesTJ8t8m3h7uqiyAhcHLwWl+xsCAhSZsLqfG7V9dbG49Lcu1CDg0bfW01Wjg0lIFpGR3aaOp1+qfhYWnYh2EpbFBuORpXBhEpbSNB6SNLqjlUaZC4SAR7KFeDAXXShJ8kn48fZ/8cO7c0D8ReEHOWGj0ZlPgoj28XQEw7VMUA90cUJm515eSZIQ3L0922QuYCUPaUPFnO9JRqzo3DuMOsvZZ338MPeM51pkUEx7MtSNKA4+ss+caj+QgW+RrsSyww2PDLQ2EjvBLHewd4mxs5GC07Vm7aBqhy6gZDiUzHbXqVLoazBhpiwyeNRS+sgo+xsoqvcWfdNs79M5/RtPFqjjM78sYVvozQ6+C55N9v1hgmy6yBDNvfOHOD9Z2E="
  app: abhi-testing-app
  on:
    repo: AbhinavSubramanian/testing
env:
  global:
    secure: RRE0apZNlZ8BaoJRK4p7IF0904AbThUnlyV52fgg4C8u8QQkZ3d6JhtQzystctqgZUmGgRPx15BQrqSArYDL7YPC0rsUzsmqt7KWiBeE1LOUjJJmEEigryVMF6X1awAI4u7N0H01Rkt6sm1u53azYcCeFiI2EZC7paSRNdLMeZEm6G5ypg7O+2AG9o8DmYIU/DBXFUGJy1gOskXhdENq0mEzYrxlyVHdBwKepHkFDiDEyrAzJSKDxSNo8OfEtko3eYc2yr/kFnhQtyLa1ynbkawqSp1DhFZt+xCNaAe2EFKKJYcHhJTSiWOWqPKEqkL6MFbWBFRbydlCZpolPIYzfiHn++3/HIFSKKZQsW6APA7BoXfwe250Y12OLEx+rm5bh48Q0VR3Dqa6QqUJ8UkLRChXrr/L+vNWFTVnT9oK29CujMynwu7tJm6He2+4Mj6XwHpDxunSAWavYZ7Es5X3wt6lT5Bo7nrvNpQU6IyRkcjCsYo6LpQjk78A19O+xh+AwGjJP1EKv/xKcHHaAcyRculhpn4UORBFmB/rXgBZgicvKaqFuxNx3JjmuciDLRAqnYbpFokbnnV4cAPHOl7x//Vn7hj+MecGWxCHC2k1HucpcBpJ/Nn2PGyFXqMI6U9NFVKkrIU9QnG0VtVyXnXXJmOL5/MN/uVficLX0+Vw6IM=
